import Provider from "@/Provider";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import 'leaflet/dist/leaflet.css';

export const metadata: Metadata = {
  title: "Snapcart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-linear-to-b from-green-50 to white">
        <Provider>
          <StoreProvider>{children}</StoreProvider>
        </Provider>
        <ToastContainer />
      </body>
    </html>
  );
}
